// See https://aka.ms/new-console-template for more information
using CH34x_Config;
using Newtonsoft.Json;

class Program
{
    /// <summary>
    /// CH34x EEPROM Configuration App
    /// </summary>
    /// <param name="target">COM Port</param>
    /// <param name="v">Print verbose.</param>
    /// <param name="l">Print list of COM ports</param>
    /// <param name="p">Print chip property. Then exit.</param>
    /// <param name="r">Print chip configuration. Then exit.</param>
    /// <param name="w">Write chip configuration.</param>
    /// <param name="initialize">Initialize EEPROM (Need to set for first use!)</param>
    /// <param name="vid">USB VID(Hex)</param>
    /// <param name="pid">USB PID(Hex)</param>
    /// <param name="useSn">Use EEPROM Serial [True|False]</param>
    /// <param name="maxPower">Max Power (mA)</param>
    /// <param name="serial">Serial String(Length: 1-8)</param>
    /// <param name="product">Product String(Length: 1-18)</param>
    /// <param name="clearProduct">Clear Product String</param>
    /// <param name="dryRun">Do not perform write action.</param>
    /// <returns></returns>
    public static int Main
        (string target = "COM5",
        bool v = false,
        bool l = false,
        bool p = false,
        bool r = false,
        bool w = false,
        bool initialize = false,
        string? vid = null,
        string? pid = null,
        bool? useSn = null,
        string? maxPower = null,
        string? serial = null,
        string? product = null,
        bool clearProduct = false,
        bool? dryRun = false) {

        if (v) { Console.WriteLine("Target port: " + target); };

        if (v) { Console.WriteLine("Library version: " + CH34x.GetLibraryVersion()); };

        if (l)
        {
            Console.WriteLine("List of COM ports:");
            List<string> ports = ListComPorts();
            foreach (string port in ports)
            {
                Console.WriteLine(port);
            }

            return 0;
        }


        if (target == null || (p == r == w == false))
        {
            System.CommandLine.DragonFruit.CommandLine.ExecuteAssembly(typeof(AutoGeneratedProgram).Assembly, new string[] { "-h" }, "");

            return 0;
        }

        CH34x ch34x;
        try
        {
            ch34x = new CH34x(target);
        }
        catch
        {
            Console.Error.WriteLine("The specified device is not CH34x. Exit...");

            return -1;
        }

        // property
        if (p)
        {
            Console.WriteLine("Property:");
            pp(ch34x.property);
            return 0;
        }

        // read EEPROM
        if (r)
        {
            ch34x.ReadChipConfiguration();

            if (ch34x.configReadSuccess)
            {
                if (v) { Console.WriteLine("Success to read chip configuration!"); };

                Console.WriteLine("\nCurrent configuration:");
                pp(ch34x.configuration);
                Console.WriteLine("\nCurrent configuration(in hex):");
                pb(ch34x.configuration.ToBytes());
            }
            else
            {
                Console.Error.WriteLine("Failed to read chip configuration!");
                Console.Error.WriteLine(ch34x.configReadErrReason);
                return -1;
            }

            return 0;
        }

        // write EEPROM
        if (w)
        {
            ch34x.ReadChipConfiguration();
            if (ch34x.configReadSuccess)
            {
                if (v) { Console.WriteLine("Success to read chip configuration!"); };
            }
            else
            {
                Console.Error.WriteLine("Failed to read chip configuration!");
                Console.Error.WriteLine(ch34x.configReadErrReason);
                
                return -1;
            }

            if (initialize == true)
                ch34x.InitializeEEPROM();
            if (vid != null)
                ch34x.SetVid(UInt16.Parse(vid, System.Globalization.NumberStyles.HexNumber));
            if (pid != null)
                ch34x.SetPid(UInt16.Parse(pid, System.Globalization.NumberStyles.HexNumber));
            if (useSn != null)
            {
                if (useSn == true)
                {
                    ch34x.EnableSerialNumber();
                }
                else
                {
                    ch34x.DisableSerialNumber();
                }
            }

            if (maxPower != null)
                ch34x.SetMaxPower(UInt16.Parse(maxPower));
            if (serial != null)
                ch34x.SetSerialNumber(serial);
            if (product != null)
                ch34x.SetProductString(product);
            if (clearProduct)
                ch34x.ClearProductString();


            Console.WriteLine("\nNew configuration:");
            pp(ch34x.configuration);
            Console.WriteLine("\nNew configuration(in hex):");
            pb(ch34x.configuration.ToBytes());
            var tbw = ch34x.configuration.ToBytes();

            if (dryRun == false)
            {
                ch34x.SaveChipConfiguration();

                ch34x.ReadChipConfiguration();
                if (ch34x.configReadSuccess)
                {
                    if (v) { Console.WriteLine("Success to read chip configuration!!"); };
                }
                else
                {
                    Console.Error.WriteLine("Failed to read chip configuration!");
                    Console.Error.WriteLine(ch34x.configReadErrReason);
                    return -1;
                }

                Console.WriteLine("\nCurrent configuration:");
                pp(ch34x.configuration);
                Console.WriteLine("\nCurrent configuration(in hex):");
                pb(ch34x.configuration.ToBytes());

                bool isDifferent = false;
                for(int i = 0; i < tbw.Length; i++)
                {
                    var curr = ch34x.configuration.ToBytes();
                    if(curr[i] != tbw[i])
                    {
                        Console.Error.WriteLine("Err in " + i);
                        isDifferent = true;
                        break;
                    }
                }

                if (isDifferent)
                {
                    Console.Error.WriteLine("\nVerification failed!!");
                    return -1;
                }else
                {
                    Console.WriteLine("Verification Success.");
                }
            }
            else
            {
                Console.WriteLine("Do not perform write action when --dry-run is set.");
            }

            return 0;
        }

        return 0;
    }

    private static List<string> ListComPorts()
    {
        var items = new List<string>();
        const string com_regex = "COM([1-9][0-9]?[0-9]?)";

        var CheckComNum = new System.Text.RegularExpressions.Regex(com_regex);
        System.Management.ManagementClass mcPnPEntity = new System.Management.ManagementClass("Win32_PnPEntity");
        System.Management.ManagementObjectCollection manageObjCol = mcPnPEntity.GetInstances();

        foreach (System.Management.ManagementObject manageObj in manageObjCol)
        {
            var namePropertyValue = manageObj.GetPropertyValue("Name");
            if (namePropertyValue == null)
            {
                continue;
            }
            string name = namePropertyValue.ToString();
            if (CheckComNum.IsMatch(name))
            {
                items.Add(name);
            }
        }
        items.Sort(delegate (string x, string y)
        {
            var mx = int.Parse(CheckComNum.Match(x).Groups[1].ToString());
            var my = int.Parse(CheckComNum.Match(y).Groups[1].ToString());

            return mx.CompareTo(my);
        });
        return items;
    }

    private static void pp(Object obj)
    {
        Console.WriteLine(JsonConvert.SerializeObject(obj, Formatting.Indented));
    }

    private static void pb(byte[] bytes)
    {
        Console.WriteLine(BitConverter.ToString(bytes).Replace("-", " "));
    }
}